# Generated by Django 2.2.6 on 2019-10-20 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME of Guide')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('no_of_people_handled', models.IntegerField()),
                ('location', models.CharField(max_length=500, verbose_name='location')),
                ('rate_per_hour', models.IntegerField()),
                ('native_language', models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi'), ('MAL', 'Malayalam'), ('TAM', 'Tamil')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, verbose_name='location')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('lang_known', models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi'), ('MAL', 'Malayalam'), ('TAM', 'Tamil')], max_length=3)),
                ('expense_type', models.CharField(choices=[('ECO', 'Economy'), ('BAS', 'Basic'), ('LUX', 'Luxury')], max_length=3)),
            ],
        ),
    ]
